# Generated by Django 3.2.3 on 2021-07-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='ColourVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColorName', models.CharField(max_length=20, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='TextureVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextureName', models.CharField(max_length=20, verbose_name='Textura')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoP',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('image', models.ImageField(upload_to='product_images')),
                ('descritption', models.TextField()),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('available_colours', models.ManyToManyField(to='venta.ColourVariation')),
                ('available_texture', models.ManyToManyField(to='venta.TextureVariation')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.category')),
            ],
            options={
                'permissions': (('administrador', 'Es Administrador'), ('usuario', 'Es Usuario')),
            },
        ),
    ]
