# Generated by Django 3.2.3 on 2021-07-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourvariation',
            name='ColorName',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='texturevariation',
            name='TextureName',
            field=models.CharField(max_length=20, verbose_name='Textura'),
        ),
    ]
