# Generated by Django 3.2.3 on 2021-07-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20210705_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productop',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
